const data = {
  products: [
    {
      _id: 1,
      name: "Amazon Echo",
      category: "Electronic Devices",
      image: "/image/amazon-echo-1.jpg",
      price: 60,
      brand: "Amazon",
      rating: 4,
      numOfReview: 10,
      description: "Very good smart speakers",
      vendor: "Amazon",
    },
    {
      _id: 2,
      name: "Sony Headphones",
      category: "Electronic Devices",
      image: "/image/sony-headphones-1.jpg",
      price: 40,
      brand: "Sony",
      rating: 4,
      numOfReview: 7,
      description: "Good Headphones for comfort listening",
      vendor: "Sony Electronics",
    },
    {
      _id: 3,
      name: "White Fashion sneakers",
      category: "Shoes",
      image: "/image/white-sneakers-1.jpg",
      price: 25,
      brand: "Fashion",
      rating: 5,
      numOfReview: 23,
      description: "comfortable white shoes, good for running",
      vendor: "Xian Duan",
    },
    {
      _id: 4,
      name: "Blue Stilettos",
      category: "Shoes",
      image: "/image/blue-lady-shoes-1.jpg",
      price: 150,
      brand: "Versace",
      rating: 4,
      numOfReview: 3,
      description: "Very comfortable shoes from Donatello Versace",
      vendor: "Versace",
    },
    {
      _id: 5,
      name: "Green Suede Brogues",
      category: "Shoes",
      image: "/image/green-brogues-1.jpg",
      price: 133,
      brand: "Oxford's",
      rating: 4,
      numOfReview: 21,
      description: "Fashionable Brogues for the fashionable man",
      vendor: "Oxford's Shoes",
    },
    {
      _id: 6,
      name: "Rayban Aviator Sunglasses",
      category: "Sunglasses",
      image: "/image/rayban-sunglasses-1.jpg",
      price: 180,
      brand: "Rayban",
      rating: 5,
      numOfReview: 6,
      description: "Good sunglasses, protects the eyes",
      vendor: "Rayban Sunglasses",
    },
    {
      _id: 7,
      name: "Red Old Skool Vans",
      category: "Shoes",
      image: "/image/red-vans-1.jpg",
      price: 50,
      brand: "Vans",
      rating: 5,
      numOfReview: 58,
      description: '"Off the Wall!"',
      vendor: "Vans",
    },
    {
      _id: 8,
      name: "White Puma Creepers",
      category: "Shoes",
      image: "/image/white-puma-1.jpg",
      price: 65,
      brand: "Puma",
      rating: 4,
      numOfReview: 12,
      description: "Awesome Puma shoes 🤮",
      vendor: "Puma",
    },
  ],
};

export default data;
